name: hello-world

on:
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!apps/**"
      - "apps/portfolio/hello-world/**"
  push:
    branches:
      - main
    paths:
      - "**"
      - "!apps/**"
      - "apps/portfolio/hello-world/**"

permissions:
  contents: read
  id-token: write

jobs:
  hello-world:
    uses: ./.github/workflows/project-cicd.yml
    with:
      aws_region: us-east-1
      deploy_pipeline_name: hello-world-prod
      deploy_pipeline_source_action_name: Source
      project_root: apps/portfolio/hello-world
